config/routes.rb
Rails.application.routes.draw do

  resources :garages do
    resources :comments
  end

  get 'search', to: 'search#search'

  post "/sessions" => "sessions#create", as: "sessions"
  get "/login" => "sessions#new", as: "new_session"
  delete "/logout" => "sessions#destroy", as: "logout"
  get "sessions/two_factor"

  post "authy/callback" => 'authy#callback'
  get "authy/status" => 'authy#one_touch_status'
  post "authy/send_token"
  post "authy/verify"

  get "/user_doc" => "users#doc", as: "doc"

  resources :users, only: [:home, :new, :create]
  
  root 'users#home'

end

app/views/layouts/_header.html.erb
<header>
  <nav>
    <% if logged_in? %>
      <%= "Hi " + current_user.username  %>
      <%= link_to "Home", garages_path %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_session_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassicGarage</title>
  <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/authy-forms.css/2.2/form.authy.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/authy-forms.js/2.2/form.authy.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>
  
</body>
</html>